FROM rstudio/plumber:v1.0.0

# 1) Install only paws/jsonlite
RUN Rscript -e "install.packages(c('jsonlite', 'httr'), repos='https://cran.rstudio.com')"

# 2) Install X-Ray daemon and netcat
# ENV AWS_EC2_METADATA_DISABLED=true
RUN apt-get update && apt-get install -y curl unzip netcat-openbsd && \
    curl -fsSL https://s3.amazonaws.com/aws-xray-assets.us-east-1/xray-daemon/aws-xray-daemon-linux-3.x.zip \
      -o /tmp/xray.zip && unzip /tmp/xray.zip -d /usr/local/bin && chmod +x /usr/local/bin/xray && \
    rm -rf /var/lib/apt/lists/* /tmp/xray.zip

WORKDIR /opt/app
COPY plumber.R plumber.R /opt/app/

EXPOSE 8080

ENTRYPOINT ["bash","-lc","/usr/local/bin/xray --region ${AWS_REGION:-ap-southeast-2} & echo 'Waiting for X-Ray daemon to be ready...' && sleep 3 && for i in {1..10}; do nc -z 127.0.0.1 2000 && break || sleep 1; done && echo 'X-Ray daemon ready, starting R...' && R -e \"pr <- plumber::plumb('/opt/app/plumber.R'); pr\\$run(host='0.0.0.0', port=8080)\""]
