FROM rstudio/plumber:v1.0.0

# 1) Install only paws/jsonlite
RUN Rscript -e "install.packages(c('jsonlite', 'httr'), repos='https://cran.rstudio.com')"

# 2) Install X-Ray daemon and netcat
# ENV AWS_EC2_METADATA_DISABLED=true
RUN apt-get update && apt-get install -y curl unzip netcat-openbsd && \
    curl -fsSL https://s3.amazonaws.com/aws-xray-assets.us-east-1/xray-daemon/aws-xray-daemon-linux-3.x.zip \
      -o /tmp/xray.zip && unzip /tmp/xray.zip -d /usr/local/bin && chmod +x /usr/local/bin/xray && \
    rm -rf /var/lib/apt/lists/* /tmp/xray.zip

WORKDIR /opt/app
COPY plumber.R start.sh /opt/app/
RUN chmod +x /opt/app/start.sh

EXPOSE 8080

ENTRYPOINT ["/opt/app/start.sh"]
